---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: dns
    box: bento/centos-7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: update
verifier:
  name: testinfra
  lint:
    name: flake8
