---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: dns
    box: bento/centos-7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ['ANSIBLE0016']
scenario:
  name: update
  test_sequence:
    - destroy
    - lint
    - create
    - converge
    # stat module makes this impossible to pass
    # - idempotence
    - verify
verifier:
  name: testinfra
  lint:
    name: flake8
