---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    set -e
    yamllint .
    ansible-lint -x 503,
platforms:
  - name: ns1
    image: bandit145/centos7-os-ansible
    privileged: true
    pre_build_image: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ns2
    image: bandit145/centos7-os-ansible
    privileged: true
    pre_build_image: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ['ANSIBLE0016']
scenario:
  name: update
verifier:
  name: testinfra
