---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: install firewalld
      yum:
        name: firewalld
        state: present

    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: true


- name: Prep ns1
  hosts: ns1
  gather_facts: false
  tasks:
    - name: stat test.com
      stat:
        path: /var/named/db.test.com
      register: test_exists

    - name: copy file for test
      copy:
        src: "{{ item }}"
        dest: /var/named/
      when: not test_exists.stat.exists
      loop:
        - db.test.com
        - db.delete.com
