---
language: python
python:
  - "3.6"
install: 
  - pip install -r requirements.txt
services:
  - docker

stages:
- test
jobs:
  include:
  - stage: test
    script:
      - molecule --debug test --all
    if: type = pull_request
