---
# tasks file for ansible-bind

- name: main | open firewall for nonsecure dns
  firewalld:
    port: "{{item}}"
    permanent: true
    immediate: true
    state: enabled
  when: isc_bind_insecure
  loop:
    - 53/udp
    - 53/tcp

- include_tasks: secure_dns.yml
  when: isc_bind_secure

- name: main | install bind packages
  yum:
    name: 
      - bind
      - stunnel
    state: present

- name: main | start bind
  service:
    name: named
    state: started
    enabled: true
    use: service

- include_tasks: zone_updates.yml
  when: isc_bind_zones is defined

- name: main | copy bind config
  template:
    src: named.conf
    dest: /etc/named.conf
    validate: /usr/sbin/named-checkconf %s
  notify: rndc_reconfig
