---
# tasks file for ansible-bind

- name: main | install bind
  yum:
    name: bind
    state: present

- name: main | start bind
  service:
    name: named
    state: started
    enabled: true
    use: service

- name: main | find zone files
  find:
    path: /var/named
    patterns: "db.*"
  register: existing_zones

- name: main | append db. to list
  set_fact:
    temp_zone_names: "{{temp_zone_names}} db.{{item}} "
  loop: lookup('subelements',isc_bind_zones,'name')

- name: main | find unused zones
  set_fact:
    destroy_zones: "{{existing_zones | difference(temp_zone_names | split(' '))}}"

- name: main | remove unspecified zones
  file:
    path: /var/named/{{item}}
    state: absent
  loop: destroy_zones

- name: main | create zones
  template:
    src: zone.j2
    dest: /var/named/db.{{item.name}}
    validate: /usr/sbin/named-checkzone {{item.name}} %s
  loop: "{{isc_bind_zones}}"
  notify: rndc_reload

- name: main | copy bind config
  template:
    src: named.conf
    dest: /etc/named.conf
    validate: /usr/sbin/named-checkconf
  notify: rndc_reconfig
