---
# tasks file for ansible-bind

- name: main | install bind
  yum:
    name: bind
    state: present

- name: main | start bind
  service:
    name: named
    state: started
    enabled: true
    use: service

- include_tasks: zone_updates.yml
  when: isc_bind_zones is defined

- name: main | copy bind config
  template:
    src: named.conf
    dest: /etc/named.conf
    validate: /usr/sbin/named-checkconf
  notify: rndc_reconfig
