---
# tasks file for ansible-bind

- name: main | create user for stunnel
  user:
    name: stunnel

- name: main | open firewall for nonsecure dns
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  when: isc_bind_insecure | bool
  loop:
    - 53/udp
    - 53/tcp

- name: main | install bind packages
  yum:
    name:
      - bind
      - bind-utils
      - stunnel
      - nginx
      - go
      - git
    state: present

- name: main | create git clone location
  file:
    path: /doh
    state: directory

- name: main | get DoH server
  git:
    repo: https://github.com/m13253/dns-over-https.git  # noqa 401
    dest: /doh
    update: false
    version: "{{ isc_bind_doh_server_version | default('master') }}"
  register: git_clone

- name: main | compile and install as systemd service
  make:
    chdir: /doh
    target: install
  register: doh_server
  when: git_clone.changed | bool

- name: main | copy stunnel systemd file
  copy:
    src: stunnel.service
    dest: /usr/lib/systemd/system/
  register: stunnel_service

# this is needed to make the stunnel service available for later
- name: main | reload daemon
  systemd:
    daemon_reload: true
  when: stunnel_service.changed | bool or doh_server.changed | bool

- include_tasks: secure_dns.yml
  when: isc_bind_secure | bool

- name: main | create logging directory
  file:
    path: /var/named/log
    owner: named
    group: named
    state: directory

- name: main | start bind
  service:
    name: named
    state: started
    enabled: true
    use: service

- include_tasks: zone_updates.yml
  when: isc_bind_zones is defined

- name: main | copy bind config
  template:
    src: named.conf
    dest: /etc/named.conf
    owner: named
    group: named
    validate: /usr/sbin/named-checkconf %s
  notify: rndc_reconfig
