---
# handlers file for ansible-bind

- name: rndc_reload
  command: rndc reload

- name: rndc_reconfig
  command: rndc reconfig

- name: enable_stunnel
  service:
    name: stunnel
    status: restarted
    enabled: true
